spring.application.name=SmartConsult

spring.datasource.url=jdbc:mysql://localhost:3306/healthcare_db
spring.datasource.username=root
spring.datasource.password=2003

spring.jpa.hibernate.ddl-auto=update

jwt.secret=smartconsult-secret-key-should-be-long
jwt.expiration=86400000